name = "kite-conditions"
compatibility_date = "2024-12-01"
main = "./dist/index.js"

[assets]
directory = "./public"

# D1 Database — stores spots + user preferences
[[d1_databases]]
binding = "DB"
database_name = "kite-conditions-db"
database_id = "e334d32d-94ef-4ba2-ae43-3d175b1420f0"

# KV Namespace — caches Open-Meteo forecast responses
[[kv_namespaces]]
binding = "CACHE"
id = "bbe782b255734d20b8e672581f0dfbcf"
